# Generated by Django 3.2.5 on 2021-08-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='news_per_page',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
