# Generated by Django 3.2.5 on 2021-08-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_news_per_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='news_per_page',
            new_name='posts_per_page',
        ),
    ]
