# Generated by Django 3.2.5 on 2021-08-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlogpost',
            old_name='composer',
            new_name='music',
        ),
        migrations.AlterField(
            model_name='vlogpost',
            name='itunes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vlogpost',
            name='lyrics',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='vlogpost',
            name='spotify',
            field=models.URLField(blank=True, null=True),
        ),
    ]
