# Generated by Django 3.2.5 on 2021-08-04 22:04

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0004_alter_vlogpost_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlogpost',
            name='youtube',
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(default='#'),
        ),
    ]
