# Generated by Django 3.2.5 on 2021-08-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0006_alter_vlogpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='video',
            new_name='vlog_post',
        ),
    ]
