# Generated by Django 3.2.5 on 2021-08-04 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_rename_news_per_page_profile_posts_per_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=45)),
                ('artist_name', models.CharField(max_length=100)),
                ('lyrics', models.CharField(max_length=110)),
                ('composer', models.CharField(max_length=110)),
                ('arranged', models.CharField(max_length=110)),
                ('producer', models.CharField(max_length=110)),
                ('youtube', models.URLField()),
                ('spotify', models.URLField()),
                ('itunes', models.URLField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlog.vlogpost')),
            ],
        ),
    ]
