# Generated by Django 3.2.5 on 2021-08-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0003_alter_vlogpost_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlogpost',
            name='youtube',
            field=models.URLField(default='#'),
        ),
    ]
