# Generated by Django 3.2.5 on 2021-08-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='news_per_page',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
