# Generated by Django 3.2.5 on 2021-08-12 19:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20210802_2338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='NewsPost',
        ),
    ]
